In [ ]:
#1. Demonstrate three different methods for creating identical 2D arrays in NumPy.
Provide the code for each method and the final output after each method.

# Method 1: Using numpy.array()
import numpy as np
np
<module 'numpy' from '/opt/conda/lib/python3.10/site-packages/numpy/__init__.py'>
array1 = np.array([[1, 2, 3], [4, 5, 6]])
print("Method 1 - numpy.array():")
Method 1 - numpy.array():

print(array1)
[[1 2 3]
 [4 5 6]]


# Method 2: Create a 2D array using numpy.zeros()
array2 = np.zeros((2, 3), dtype=int)
array2[0] = [1, 2, 3]
array2[1] = [4, 5, 6]
print("\nMethod 2 - numpy.zeros():")
print(array2)

Method 2 - numpy.zeros():
[[1 2 3]
 [4 5 6]]

# Method 3: Create a 1D array and then reshape it to a 2D array
array3 = np.arange(1, 7).reshape(2, 3)
print("\nMethod 3 - numpy.reshape():")
print(array3)

Method 3 - numpy.reshape():
[[1 2 3]
 [4 5 6]]


In [ ]:
#2. Using the Numpy function, generate an array of 100 evenly spaced numbers between 1 and 10 and Reshape that 1D array into a 2D array

#
import numpy as np

# Generate an array of 100 evenly spaced numbers between 1 and 10
array_1d = np.linspace(1, 10, 100)

# Reshape the 1D array into a 2D array (for example, 10 rows and 10 columns)
array_2d = array_1d.reshape(10, 10)

# Print the resulting 2D array
print("2D Array (10x10):")
print(array_2d)

# Expected Output:

2D Array (10x10):
[[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545  1.54545455  1.63636364  1.72727273  1.81818182]
 [ 1.90909091  2.          2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455  2.63636364  2.72727273]
 [ 2.81818182  2.90909091  3.          3.09090909  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364]
 [ 3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818  4.27272727  4.36363636  4.45454545  4.54545455]
 [ 4.63636364  4.72727273  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727  5.36363636  5.45454545]
 [ 5.54545455  5.63636364  5.72727273  5.81818182  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636]
 [ 6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091  7.          7.09090909  7.18181818  7.27272727]
 [ 7.36363636  7.45454545  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.          8.09090909  8.18181818]
 [ 8.27272727  8.36363636  8.45454545  8.54545455  8.63636364  8.72727273  8.81818182  8.90909091  9.          9.09090909]
 [ 9.18181818  9.27272727  9.36363636  9.45454545  9.54545455  9.63636364  9.72727273  9.81818182  9.90909091 10.        ]]


In [ ]:
#3.  Explain the following terms

# The difference in np.array, np.asarray and np.asanyarray
# The difference between Deep copy and shallow copy

Certainly! Let's break down each set of terms for better clarity:

### NumPy Array Functions

1. **`np.array`**:
   - This function creates a new NumPy array from a given input (like a list, tuple, or another array). It copies the input data into a new array object.
   - You can specify parameters like `dtype`, `order`, etc., during creation.
   - Example: `np.array([1, 2, 3])` creates a new array `[1, 2, 3]`.

2. **`np.asarray`**:
   - This function converts the input to an array, but it does not create a new array if the input is already an array of the desired type. Instead, it returns the original array if it already satisfies the type.
   - It's more memory efficient when you're dealing with arrays that don't need to be copied.
   - Example: `np.asarray(np.array([1, 2, 3]))` returns the same array without copying.

3. **`np.asanyarray`**:
   - Similar to `np.asarray`, but it allows for subclasses of arrays (like `np.matrix` or other array-like objects). It will return a view of the input data but will not enforce the return type to be exactly a NumPy array as `np.asarray` does.
   - This is useful when you want to ensure the output is array-like, inclusive of subclasses.
   - Example: `np.asanyarray(np.matrix([[1, 2], [3, 4]]))` returns a matrix rather than converting it to a standard array.

### Deep Copy vs. Shallow Copy

1. **Shallow Copy**:
   - A shallow copy creates a new object, but it populates this new object with references to the child objects found in the original. Therefore, changes to mutable objects inside the original will affect those in the shallow copy as they are referencing the same objects.
   - In Python, you can create a shallow copy using the `copy` module: `import copy; shallow_copy = copy.copy(original)`.
   - Example: 

    import copy
     original = [1, [2, 3]]
     shallow_copy = copy.copy(original)
     shallow_copy[1][0] = 'changed'
     print(original)  # Output: [1, ['changed', 3]]
     

2. **Deep Copy**:
   - A deep copy creates a new object along with recursively copying all objects found in the original. This means that any changes made to the nested objects in a deep copy do not affect the original and vice versa.
   - In Python, use `copy.deepcopy()` for creating a deep copy: `deep_copy = copy.deepcopy(original)`.
   - Example:

    import copy
     original = [1, [2, 3]]
     deep_copy = copy.deepcopy(original)
     deep_copy[1][0] = 'changed'
     print(original)  # Output: [1, [2, 3]]
     

### Summary

- **NumPy Functions**:
  - `np.array`: Always creates a new array.
  - `np.asarray`: Converts to an array, may just return the original.
  - `np.asanyarray`: Returns an array, including subclasses.

- **Copying**:
  - Shallow Copy: Creates a new object with references; changes in nested mutable objects are reflected in both copies.
  - Deep Copy: Creates a completely independent copy; changes in nested objects do not affect the original. 

This distinction helps in memory management and understanding how modifications affect data structures in programming. 

In [ ]:
#4. Generate a 3×3 array with random floating-point numbers between 5 and 20. Then, round each number in the array to 2 decimal places.

# 
import numpy as np

# Generate a 3x3 array with random floats between 5 and 20
random_array = np.random.uniform(5, 20, (3, 3))

# Round each number to 2 decimal places
rounded_array = np.round(random_array, 2)

print(rounded_array)


In [ ]:
#5. Create a NumPy array with random integers Between 1 and 10 of shape (5,6). After creating the array perform the following operations:

 # Extract all even integers from array.

 # Extract all odd integers from array.

## 
import numpy as np

# Create a 5x6 array with random integers between 1 and 10
random_int_array = np.random.randint(1, 11, size=(5, 6))

# Display the original array
print("Original Array:")
print(random_int_array)

# a) Extract all even integers
even_integers = random_int_array[random_int_array % 2 == 0]

# b) Extract all odd integers
odd_integers = random_int_array[random_int_array % 2 != 0]

# Display the results
print("\nEven Integers:")
print(even_integers)

print("\nOdd Integers:")
print(odd_integers)


In [ ]:
#6. Create a 3D NumPy array of shape (3,3,3) containing random integers Between 1 and 10. Perform the following operations: 
a) Find the indices of the maximum values along each depth level (third axis).
b) Perform element-wise multiplication of between both array

##
import numpy as np

# Create a 3x3x3 array with random integers between 1 and 10
random_3d_array = np.random.randint(1, 11, size=(3, 3, 3))

# Display the original array
print("Original 3D Array:")
print(random_3d_array)

# a) Find the indices of the maximum values along each depth level (third axis)
max_indices = np.argmax(random_3d_array, axis=2)

# Display the indices of maximum values
print("\nIndices of Maximum Values along each depth level:")
print(max_indices)

# b) Perform element-wise multiplication of the array with itself
elementwise_multiplication = random_3d_array * random_3d_array

# Display the result of element-wise multiplication
print("\nElement-wise Multiplication of the Array with Itself:")
print(elementwise_multiplication)


In [ ]:
#7. Clean and transform the 'Phone' column in the sample dataset to remove non-numeric characters and convert it to a numeric data type.
Also display the table attributes and data types of each column.

##
import pandas as pd
import numpy as np

# Sample data based on the provided dataset format
data = {
    'ID': [785, 786, 787, 788, 789, 790, 791, 792, 793],
    'Name': ['Jean Browning', 'Lawrence Gregory', 'Christine Payne', 'Barbara Ramirez', 'Ruben Hammond', 'Donald Nash', 'Angelica Anthony', 'Claire Glass', 'Leslie Curry'],
    'Email': ['clineangela@example.net', 'yolanda30@example.com', 'ihouse@example.org', 'kiddmakayla@example.com', 'delgadodarren@example.com', 'albertsummers@example.net', 'andre30@example.org', 'vanessacox@example.com', 'mike30@example.org'],
    'Phone': ['081.103.9205x63568', '969662902', '+1-656-627-9739x10338', '956-042-9355x04371', '001-899-366-2788x46956', '412-275-7723x5364', '(396)368-5082', '263-938-1564x0528', '(812)017-6908'],
    'Date_of_Birth': ['11-01-1980', '01-05-2013', '13-06-1913', '06-02-1919', '10-11-1954', '08-08-1953', '12-11-1943', '24-10-1980', '']
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
print(df)

# Clean and transform the 'Phone' column
df['Phone'] = df['Phone'].str.replace(r'\D', '', regex=True)  # Remove non-numeric characters
df['Phone'] = pd.to_numeric(df['Phone'], errors='coerce')   # Convert to numeric, NaN for non-convertible values

# Display the cleaned 'Phone' column
print("\nCleaned 'Phone' Column:")
print(df['Phone'])

# Display DataFrame information including data types
print("\nDataFrame Attributes and Data Types:")
print(df.dtypes)


In [ ]:
#8. Perform the following tasks using people dataset: 

a) Read the 'data.csv' file using pandas, skipping the first 50 rows. 
b) Only read the columns: 'Last Name', ‘Gender’, ’Email’, ‘Phone’ and ‘Salary’ from the file.
 c) Display the first 10 rows of the filtered dataset. 
d) Extract the ‘Salary’' column as a Series and display its last 5 values.

##
import pandas as pd

# a) Read the 'data.csv' file, skipping the first 50 rows
df = pd.read_csv('data.csv', skiprows=50)

# b) Only read the specified columns
column_names = ['Last Name', 'Gender', 'Email', 'Phone', 'Salary']
filtered_df = df[column_names]

# c) Display the first 10 rows of the filtered dataset
print("First 10 rows of the filtered dataset:")
print(filtered_df.head(10))

# d) Extract the 'Salary' column as a Series and display its last 5 values
salary_series = filtered_df['Salary']
print("\nLast 5 values of the 'Salary' column:")
print(salary_series.tail(5))


In [ ]:
#9.  Filter and select rows from the People_Dataset, where the “Last Name' column contains the name 'Duke', 'Gender' column
contains the word Female and ‘Salary’ should Be less than 85000.

##
import pandas as pd

# Load the dataset
df = pd.read_csv('data.csv')  # Make sure to adjust the file path accordingly

# Filter based on the specified criteria
filtered_df = df[
    (df['Last Name'].str.contains('Duke', na=False)) &
    (df['Gender'] == 'Female') &
    (df['Salary'] < 85000)
]

# Display the filtered results
print("Filtered Rows:")
print(filtered_df)
